
import { Category, EbookItem } from './types';

export const CATEGORIES = [
  { id: 'all', name: '전체', icon: '📚' },
  { id: 'money', name: Category.MONEY, icon: '💰' },
  { id: 'career', name: Category.CAREER, icon: '💼' },
  { id: 'life', name: Category.LIFE, icon: '🌱' },
  { id: 'design', name: Category.DESIGN, icon: '🎨' },
  { id: 'programming', name: Category.PROGRAMMING, icon: '💻' },
  { id: 'hobby', name: Category.HOBBY, icon: '🪁' },
  { id: 'marketing', name: Category.MARKETING, icon: '📢' },
];

export const MOCK_EBOOKS: EbookItem[] = [
  {
    id: '1',
    title: '월 100만원 추가 수익을 만드는 무자본 창업 가이드',
    authorName: '비즈니스 마스터',
    category: Category.MONEY,
    price: 19000,
    rating: 4.9,
    reviewCount: 452,
    imageUrl: 'https://picsum.photos/seed/money-book/600/800',
    pageCount: 124,
    isBestseller: true,
  },
  {
    id: '2',
    title: '현직 대기업 팀장이 알려주는 노션 워크스페이스 구축법',
    authorName: '생산성 킹',
    category: Category.CAREER,
    price: 15000,
    rating: 4.8,
    reviewCount: 89,
    imageUrl: 'https://picsum.photos/seed/notion-book/600/800',
    pageCount: 85,
    isNew: true,
  },
  {
    id: '3',
    title: '파이썬으로 주식 자동매매 프로그램 만들기 (비전공자용)',
    authorName: '코딩 요정',
    category: Category.PROGRAMMING,
    price: 39000,
    rating: 5.0,
    reviewCount: 210,
    imageUrl: 'https://picsum.photos/seed/python-book/600/800',
    pageCount: 210,
    isBestseller: true,
  },
  {
    id: '4',
    title: '아이폰 하나로 끝내는 인스타그램 감성 사진 보정법',
    authorName: '포토그래퍼 진',
    category: Category.DESIGN,
    price: 12000,
    rating: 4.7,
    reviewCount: 56,
    imageUrl: 'https://picsum.photos/seed/photo-book/600/800',
    pageCount: 62,
  },
  {
    id: '5',
    title: '평생 써먹는 가계부 작성 및 자산 관리 전략',
    authorName: '짠테크 전문가',
    category: Category.LIFE,
    price: 9900,
    rating: 4.6,
    reviewCount: 178,
    imageUrl: 'https://picsum.photos/seed/save-book/600/800',
    pageCount: 45,
  },
  {
    id: '6',
    title: '퇴사 후 한 달 만에 크몽 수익 300만원 달성한 비결',
    authorName: '프리랜서 루카',
    category: Category.MONEY,
    price: 25000,
    rating: 4.9,
    reviewCount: 322,
    imageUrl: 'https://picsum.photos/seed/freelance-book/600/800',
    pageCount: 156,
    isBestseller: true,
  },
];
